name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '.github/workflows/main.yml'

env:
  AZURE_WEBAPP_NAME: app-promed-backend-prod-dev
  AZURE_CR_NAME: promedhealthdashboard
  IMAGE_NAME: backend
  IMAGE_TAG: latest
  RESOURCE_GROUP: PromedHealth-Dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Entrypoint Script
        run: |
          ENTRYPOINT_PATH="./entrypoint.sh"
          echo "Creating entrypoint script at: $ENTRYPOINT_PATH"
          
          cat > "$ENTRYPOINT_PATH" << 'EOF'
          #!/bin/sh
          echo "Starting entrypoint script..."
          
          echo "Waiting for database to be ready..."
          DB_HOST="${MYSQL_DB_HOST:-mysql-promedhealthplue-dev.mysql.database.azure.com}"
          DB_PORT="${MYSQL_DB_PORT:-3306}"
          timeout=60
          counter=0
          while ! nc -z "$DB_HOST" "$DB_PORT"; do
              sleep 1
              counter=$((counter + 1))
              if [ $counter -ge $timeout ]; then
                  echo "Database connection timeout after ${timeout} seconds"
                  exit 1
              fi
          done

          echo "Database is available. Running migrations..."
          python manage.py migrate --noinput

          echo "Starting Gunicorn server..."
          exec gunicorn promed_backend_api.wsgi:application --workers 4 --bind 0.0.0.0:8000 --timeout 120
          EOF

          chmod +x "$ENTRYPOINT_PATH"
          echo "Entrypoint script created:"
          ls -la "$ENTRYPOINT_PATH"

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.AZURE_CR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_FULL_NAME="${{ env.AZURE_CR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          echo "Dockerfile location: $(pwd)/Dockerfile"
          
          if [ ! -f "Dockerfile" ]; then
            echo "ERROR: Dockerfile not found in $(pwd)"
            exit 1
          fi

          docker build \
            --platform linux/amd64 \
            -t "$IMAGE_FULL_NAME" \
            .

          echo "Pushing Docker image to ACR: $IMAGE_FULL_NAME"
          docker push "$IMAGE_FULL_NAME"

      - name: Azure Login for Deployment
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.AZURE_CR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Restart Azure App Service
        run: |
          echo "Restarting App Service: ${{ env.AZURE_WEBAPP_NAME }}"
          az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}

      - name: Post-deployment Health Check (Optional)
        run: |
          URL="https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/health/"
          echo "Checking app health at $URL"
          for i in {1..10}; do
            if curl -fs $URL; then
              echo "Health check passed!"
              exit 0
            else
              echo "Waiting for app to become healthy... (attempt $i)"
              sleep 5
            fi
          done
          echo "App failed health check after deployment."
          exit 1

      - name: Logout of Azure
        run: az logout
